### ISSUE TITLE
deployments fail to setup because no installation of scripts in /srv/www/horde/web/horde/bin/

### ISSUE THREAD

**Issue by boekhorstb1** [maintaina/deployments#13]
Maybe some error in the horde-isntaller?

Deployments are currently not working because this script  `/srv/www/horde/web/horde/bin/horde-sql-shell` is not present. From within the container:

````
ls: cannot access '/srv/www/web/horde/bin': No such file or directory
````
**Note**: horde-sql-shell is present twice in the vendor file:

````
# find ./ -name horde-sql-shell
./vendor/bin/horde-sql-shell
./vendor/horde/horde/bin/horde-sql-shell
````

The script has to be run form within the base-image, but it cannot be run because it is not available. See [entrypoint.sh](https://github.com/maintaina/containers/blob/master/base/bin/entrypoint.sh) on line 125:

````
## TODO: BACKGROUND THIS and everything besides making the main process pid 1
## Wait for DB connection to succeed
## TODO: Make this optional for No-DB scenarios
if [[ -n "$MYSQL_PASSWORD" ]]; then
    echo "SHOW DATABASES" >/root/conntest.sql
    echo "WAITING FOR DB CONNECTION TO SUCCEED"
    echo "For new setups, this may take some time. You may see error messages"
    until php /srv/www/horde/web/horde/bin/horde-sql-shell /root/conntest.sql &>/dev/null; do
        sleep 3
        echo "RETRYING"
    done
    echo "CONNECTION ESTABLISHED"
fi
````

**Comment by boekhorstb1** [comment]
see following [MR](https://github.com/maintaina-com/horde-installer-plugin/pull/19/files)

**Comment by ralflang** [comment]
That's not really an error but intentional. Please use vendor/bin instead. I should have been more verbose about it when I introduced that.

It basically works this way:
- Apps used to be installed to www/ but this has been changed a while back to align with js and themes packages. Apps are now installed to vendor/$vendor/$package just like every other dependency.
- Wrapper files for binaries are installed to composer config bin-dir. This is usually vendor/bin but can be configured to be anything, including usr/local/bin. These wrapper files include autoloader setup and some other niceties like creating a path to the original file. In some older versions of composer/composer, these files were not wrappers but "dumb" symlinks to the original file. This is done by composer itself.
- The horde/horde-installer-plugin links (linux) or copies (windows) only the necessary items to the web folder. At the moment this includes lib/ but in the long run it should only be the web endpoints and some static resources. I already stripped test/, bin/, script/, doc/ and some others because they have no business being web-readable.

@boekhorstb1 Can you change deployment to use vendor/bin/ instead or even better, check what composer config bin-dir says? (by default: vendor/bin)
